### ISSUE TITLE
Target EAP file does not exist

### ISSUE THREAD

**Issue by krequena** [krequena/eamodeltransfer#4]
Exporting from a DBMS to an EAP file fails with the following error:

`
Model export has finished unsuccessfully and with an exception.: pro.requena.ea.modeltransfer.exceptions.EAModelTransferException: net.ucanaccess.jdbc.UcanaccessSQLException: UCAExc:::4.0.4 given file does not exist: C:\Temp\modeltransfer\xxx_20190104_1606.eap
        at pro.requena.ea.modeltransfer.database.EADatabase.connectEap(EADatabase.java:51)
        at pro.requena.ea.modeltransfer.database.EADatabase.connect(EADatabase.java:35)
        at pro.requena.ea.modeltransfer.ModelTransfer.transfer(ModelTransfer.java:27)
`

It should create the new file.

**Comment by krequena** [comment]
Hint: https://sourceforge.net/p/ucanaccess/discussion/help/thread/0f31d949/

**Comment by krequena** [comment]
Not using autocreation, but an Sparx's standard template provided in their website as the base file which will then be filled with the source data.
See [the original source](https://www.sparxsystems.com.au/resources/repositories/index.html).
